#include "TelemetryAISchemaSync.h"
#include "TelemetryAISettings.h"
#include "HttpModule.h"
#include "Interfaces/IHttpResponse.h"
#include "Dom/JsonObject.h"
#include "Serialization/JsonSerializer.h"
#include "Misc/DateTime.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Interfaces/IPluginManager.h"

DEFINE_LOG_CATEGORY_STATIC(LogTelemetryAISchemaSync, Log, All);

namespace
{
    FString BuildSchemaUrl(const FString& Endpoint)
    {
        FString Url = Endpoint;
        if (Url.EndsWith("/"))
        {
            Url.LeftChopInline(1);
        }
        Url += "/v1/schema/current";
        return Url;
    }

    FString EscapeCppString(const FString& Input)
    {
        FString Out;
        Out.Reserve(Input.Len());
        for (TCHAR Char : Input)
        {
            if (Char == '\\')
            {
                Out += TEXT("\\\\");
            }
            else if (Char == '"')
            {
                Out += TEXT("\\\"");
            }
            else
            {
                Out.AppendChar(Char);
            }
        }
        return Out;
    }

    FString ToPascalCase(const FString& Input)
    {
        FString Out;
        bool bCapNext = true;
        for (TCHAR Char : Input)
        {
            if (FChar::IsAlnum(Char))
            {
                if (bCapNext)
                {
                    Out.AppendChar(FChar::ToUpper(Char));
                    bCapNext = false;
                }
                else
                {
                    Out.AppendChar(FChar::ToLower(Char));
                }
            }
            else
            {
                bCapNext = true;
            }
        }
        if (Out.IsEmpty())
        {
            Out = TEXT("Event");
        }
        if (FChar::IsDigit(Out[0]))
        {
            Out = TEXT("Event") + Out;
        }
        return Out;
    }

    FString MakeUniqueEnumName(const FString& Base, TSet<FString>& Used)
    {
        FString Name = Base;
        int32 Suffix = 2;
        while (Used.Contains(Name) || Name.Equals(TEXT("None"), ESearchCase::IgnoreCase) || Name.Equals(TEXT("MAX"), ESearchCase::IgnoreCase))
        {
            Name = FString::Printf(TEXT("%s_%d"), *Base, Suffix++);
        }
        Used.Add(Name);
        return Name;
    }

    FString BuildHeader(
        const TArray<TPair<FString, FString>>& EventPairs,
        int32 SchemaVersion
    ) {
        FString Header;
        Header += TEXT("// Auto-generated by TelemetryAI. Do not edit manually.\n");
        Header += FString::Printf(TEXT("// Schema version: %d\n"), SchemaVersion);
        Header += TEXT("#pragma once\n\n");
        Header += TEXT("#include \"CoreMinimal.h\"\n");
        Header += TEXT("#include \"TelemetryAIEventNames.generated.h\"\n\n");
        Header += TEXT("UENUM(BlueprintType)\n");
        Header += TEXT("enum class ETelemetryAIEventName : uint16\n{\n");
        for (const TPair<FString, FString>& Pair : EventPairs)
        {
            Header += FString::Printf(
                TEXT("    %s UMETA(DisplayName = \"%s\"),\n"),
                *Pair.Key,
                *EscapeCppString(Pair.Value)
            );
        }
        Header += TEXT("    Unknown UMETA(DisplayName = \"unknown\")\n");
        Header += TEXT("};\n\n");
        Header += TEXT("namespace TelemetryAIEventNames\n{\n");
        for (const TPair<FString, FString>& Pair : EventPairs)
        {
            Header += FString::Printf(
                TEXT("    inline constexpr const TCHAR* %s = TEXT(\"%s\");\n"),
                *Pair.Key,
                *EscapeCppString(Pair.Value)
            );
        }
        Header += TEXT("    inline constexpr const TCHAR* Unknown = TEXT(\"unknown\");\n");
        Header += TEXT("}\n\n");
        Header += TEXT("namespace TelemetryAIEvents\n{\n");
        Header += TEXT("    inline const TCHAR* ToString(ETelemetryAIEventName Name)\n");
        Header += TEXT("    {\n");
        Header += TEXT("        switch (Name)\n");
        Header += TEXT("        {\n");
        for (const TPair<FString, FString>& Pair : EventPairs)
        {
            Header += FString::Printf(
                TEXT("            case ETelemetryAIEventName::%s: return TelemetryAIEventNames::%s;\n"),
                *Pair.Key,
                *Pair.Key
            );
        }
        Header += TEXT("            default: return TEXT(\"\");\n");
        Header += TEXT("        }\n");
        Header += TEXT("    }\n");
        Header += TEXT("}\n");
        return Header;
    }

    void UpdateSettings(
        int32 SchemaVersion,
        const TArray<FString>& EventNames,
        const FString& HeaderPreview,
        const FString& ErrorMessage
    ) {
        UTelemetryAISettings* MutableSettings = GetMutableDefault<UTelemetryAISettings>();
        if (!MutableSettings)
        {
            return;
        }
        if (!ErrorMessage.IsEmpty())
        {
            MutableSettings->LastSchemaSyncError = ErrorMessage;
        }
        else
        {
            MutableSettings->ActiveSchemaVersion = SchemaVersion;
            MutableSettings->ActiveSchemaEventNames = EventNames;
            MutableSettings->GeneratedEventHeaderPreview = HeaderPreview;
            MutableSettings->LastSchemaSyncError = TEXT("");
        }
        MutableSettings->LastSchemaSyncAt = FDateTime::UtcNow().ToString();
        MutableSettings->SaveConfig();
    }
}

bool FTelemetryAISchemaSync::SyncFromSettings(bool bWriteHeader)
{
    const UTelemetryAISettings* Settings = GetDefault<UTelemetryAISettings>();
    if (!Settings)
    {
        UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("TelemetryAI settings not available."));
        return false;
    }

    if (Settings->EndpointUrl.IsEmpty() || Settings->ApiKey.IsEmpty())
    {
        UpdateSettings(0, {}, TEXT(""), TEXT("Endpoint or API key missing."));
        UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("Schema sync failed: Endpoint or API key missing."));
        return false;
    }

    const FString Url = BuildSchemaUrl(Settings->EndpointUrl);
    TSharedRef<IHttpRequest, ESPMode::ThreadSafe> Request = FHttpModule::Get().CreateRequest();
    Request->SetURL(Url);
    Request->SetVerb("GET");
    Request->SetHeader(TEXT("Accept"), TEXT("application/json"));
    Request->SetHeader(TEXT("X-Api-Key"), Settings->ApiKey);

    Request->OnProcessRequestComplete().BindLambda([bWriteHeader](FHttpRequestPtr Req, FHttpResponsePtr Response, bool bSuccess)
    {
        const int32 Code = Response.IsValid() ? Response->GetResponseCode() : 0;
        if (!bSuccess || Code != 200)
        {
            FString Error = FString::Printf(TEXT("HTTP %d: Schema sync failed"), Code);
            UpdateSettings(0, {}, TEXT(""), Error);
            UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("%s"), *Error);
            return;
        }

        TSharedPtr<FJsonObject> Root;
        const FString Body = Response->GetContentAsString();
        const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Body);
        if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid())
        {
            UpdateSettings(0, {}, TEXT(""), TEXT("Schema parse failed."));
            UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("Schema parse failed."));
            return;
        }

        int32 SchemaVersion = 0;
        if (Root->HasTypedField<EJson::Number>(TEXT("schemaVersion")))
        {
            SchemaVersion = Root->GetIntegerField(TEXT("schemaVersion"));
        }

        const TArray<TSharedPtr<FJsonValue>>* EventsJson = nullptr;
        if (!Root->TryGetArrayField(TEXT("events"), EventsJson) || !EventsJson)
        {
            UpdateSettings(0, {}, TEXT(""), TEXT("Schema has no events list."));
            UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("Schema has no events list."));
            return;
        }

        TArray<FString> EventNames;
        EventNames.Reserve(EventsJson->Num());
        TArray<TPair<FString, FString>> EventPairs;
        EventPairs.Reserve(EventsJson->Num());
        TSet<FString> UsedEnumNames;

        for (const TSharedPtr<FJsonValue>& Value : *EventsJson)
        {
            const TSharedPtr<FJsonObject> EventObj = Value.IsValid() ? Value->AsObject() : nullptr;
            if (!EventObj.IsValid())
            {
                continue;
            }
            FString EventName;
            if (!EventObj->TryGetStringField(TEXT("eventName"), EventName) || EventName.IsEmpty())
            {
                continue;
            }
            EventNames.Add(EventName);

            FString BaseEnum = ToPascalCase(EventName);
            FString UniqueEnum = MakeUniqueEnumName(BaseEnum, UsedEnumNames);
            EventPairs.Add(TPair<FString, FString>(UniqueEnum, EventName));
        }

        const FString Header = BuildHeader(EventPairs, SchemaVersion);
        UpdateSettings(SchemaVersion, EventNames, Header, TEXT(""));

        if (bWriteHeader)
        {
            TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("TelemetryAI"));
            if (!Plugin.IsValid())
            {
                UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("TelemetryAI plugin not found."));
                return;
            }
            const FString HeaderPath = FPaths::Combine(
                Plugin->GetBaseDir(),
                TEXT("Source/TelemetryAI/Public/TelemetryAIEventNames.h")
            );
            if (!FFileHelper::SaveStringToFile(Header, *HeaderPath))
            {
                UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("Failed to write header: %s"), *HeaderPath);
                return;
            }
            UE_LOG(LogTelemetryAISchemaSync, Log, TEXT("Schema synced. Header written to %s"), *HeaderPath);
        }
        else
        {
            UE_LOG(LogTelemetryAISchemaSync, Log, TEXT("Schema synced. Header preview updated."));
        }
    });

    if (!Request->ProcessRequest())
    {
        UpdateSettings(0, {}, TEXT(""), TEXT("Schema sync request failed to start."));
        UE_LOG(LogTelemetryAISchemaSync, Error, TEXT("Schema sync request failed to start."));
        return false;
    }

    return true;
}
